name: Release

on:
  push:
    branches:
      - dev
      - stable

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Setup node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Semantic release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
